export const POSITIONS = {
  Straight: [
    '69',
    'Cowgirl',
    'Doggy',
    'Girl gives oral',
    'Girl receives fingering',
    'Girl sits on face',
    'Girls legs on shoulders',
    'Guy gives oral',
    'Guy receives handjob',
    'Guy sits on face',
    'Lotus',
    'Missionary',
    'Prone',
    'Reverse cowgirl',
    'Spooning',
    'Standing reverse',
    'Standing',
    'T-square',
    'Titty fucking',
  ],
  Gay: [
    '69',
    'Doggy, partner 1 penetrates',
    'Doggy, partner 2 penetrates',
    'Frot',
    'Lotus, partner 1 penetrates',
    'Lotus, partner 2 penetrates',
    'Missionary, partner 1 penetrates',
    'Missionary, partner 2 penetrates',
    'Mutual handjob',
    'Partner 1 gives handjob',
    'Partner 1 gives oral',
    'Partner 1 rims partner 2',
    'Partner 1 sits on face',
    'Partner 2 gives handjob',
    'Partner 2 gives oral',
    'Partner 2 rims partner 1',
    'Partner 2 sits on face',
    'Piledriver, partner 1 penetrates',
    'Piledriver, partner 2 penetrates',
    'Prone, partner 1 penetrates',
    'Prone, partner 2 penetrates',
    'Reverse riding, partner 1 penetrates',
    'Reverse riding, partner 2 penetrates',
    'Spooning, partner 1 penetrates',
    'Spooning, partner 2 penetrates',
    'Standing, partner 1 penetrates',
    'Standing, partner 2 penetrates',
  ],
  Lesbian: [
    '69',
    'Double-ended toy',
    'Mutual fingering',
    'Partner 1 fingers partner 2',
    'Partner 1 gives oral',
    'Partner 1 penetrates partner 2 with toy',
    'Partner 1 sits on face',
    'Partner 2 fingers partner 1',
    'Partner 2 gives oral',
    'Partner 2 penetrates partner 1 with toy',
    'Partner 2 sits on face',
    'Scissoring',
  ],
} as const;
