export const POSITIONS = {
  Straight: [
    'Missionary',
    'Butterfly',
    'Viennese oyster',
    'Coital alignment technique',
    'Doggy',
    'Prone',
    'Leapfrog',
    'Spooning',
    'Cowgirl',
    'Reverse cowgirl',
    'Lateral coital',
    'Lotus',
    'Lap dance',
    'Standing',
    'Standing reverse',
    'Suspended congress',
    'T-square',
    'Piledriver',
    'Guy gives oral',
    'Girl gives oral',
    'Guy sits on face',
    'Girl sits on face',
    '69',
    'Guy receives handjob',
    'Girl receives fingering',
    'Titty fucking',
  ],
  Gay: [
    'Missionary, partner 1 penetrates',
    'Missionary, partner 2 penetrates',
    'Doggy, partner 1 penetrates',
    'Doggy, partner 2 penetrates',
    'Prone, partner 1 penetrates',
    'Prone, partner 2 penetrates',
    'Spooning, partner 1 penetrates',
    'Spooning, partner 2 penetrates',
    'Reverse riding, partner 1 penetrates',
    'Reverse riding, partner 2 penetrates',
    'Lotus, partner 1 penetrates',
    'Lotus, partner 2 penetrates',
    'Standing, partner 1 penetrates',
    'Standing, partner 2 penetrates',
    'Piledriver, partner 1 penetrates',
    'Piledriver, partner 2 penetrates',
    'Partner 1 gives oral',
    'Partner 2 gives oral',
    'Partner 1 sits on face',
    'Partner 2 sits on face',
    '69',
    'Frot',
    'Partner 1 receives handjob',
    'Partner 2 receives handjob',
    'Partner 1 rims partner 2',
    'Partner 2 rims partner 1',
  ],
  Lesbian: [
    'Partner 1 gives oral',
    'Partner 2 gives oral',
    'Partner 1 sits on face',
    'Partner 2 sits on face',
    '69',
    'Scissoring',
    'Tribadism',
    'Partner 1 fingers partner 2',
    'Partner 2 fingers partner 1',
    'Partner 1 penetrates partner 2 with toy',
    'Partner 2 penetrates partner 1 with toy',
    'Double-ended toy',
  ],
} as const;

// Straight couple positions
export const POSITIONS_STRAIGHT = [
  'Missionary',
  'Butterfly',
  'Viennese oyster',
  'Coital alignment technique',
  'Doggy',
  'Prone',
  'Leapfrog',
  'Spooning',
  'Cowgirl',
  'Reverse cowgirl',
  'Lateral coital',
  'Lotus',
  'Lap dance',
  'Standing',
  'Standing reverse',
  'Suspended congress',
  'T-square',
  'Piledriver',
  'Guy gives oral',
  'Girl gives oral',
  'Guy sits on face',
  'Girl sits on face',
  '69',
  'Guy receives handjob',
  'Girl receives fingering',
  'Titty fucking',
] as const;

// Gay couple positions
export const POSITIONS_GAY = [
  'Missionary, partner 1 penetrates',
  'Missionary, partner 2 penetrates',
  'Doggy, partner 1 penetrates',
  'Doggy, partner 2 penetrates',
  'Prone, partner 1 penetrates',
  'Prone, partner 2 penetrates',
  'Spooning, partner 1 penetrates',
  'Spooning, partner 2 penetrates',
  'Reverse riding, partner 1 penetrates',
  'Reverse riding, partner 2 penetrates',
  'Lotus, partner 1 penetrates',
  'Lotus, partner 2 penetrates',
  'Standing, partner 1 penetrates',
  'Standing, partner 2 penetrates',
  'Piledriver, partner 1 penetrates',
  'Piledriver, partner 2 penetrates',
  'Partner 1 gives oral',
  'Partner 2 gives oral',
  'Partner 1 sits on face',
  'Partner 2 sits on face',
  '69',
  'Frot',
  'Partner 1 receives handjob',
  'Partner 2 receives handjob',
  'Partner 1 rims partner 2',
  'Partner 2 rims partner 1',
] as const;

// Lesbian couple positions
export const POSITIONS_LESBIAN = [
  'Partner 1 gives oral',
  'Partner 2 gives oral',
  'Partner 1 sits on face',
  'Partner 2 sits on face',
  '69',
  'Scissoring',
  'Tribadism',
  'Partner 1 fingers partner 2',
  'Partner 2 fingers partner 1',
  'Partner 1 penetrates partner 2 with toy',
  'Partner 2 penetrates partner 1 with toy',
  'Double-ended toy',
] as const;

export const MIN_TIMER = 10; // seconds
export const MAX_TIMER = 600; // 10 minutes
export const DEFAULT_TIMER = 120; // 2 minutes (shown as 02:00)
export const TIMER_BOUNDARY = 180; // 3 minutes - switch from 10s to 30s increments
export const TIMER_STEP_SMALL = 10; // 10s increment below 3 minutes
export const TIMER_STEP_LARGE = 30; // 30s increment at/above 3 minutes
